feat: add ecma_parser deps
swc-project/plugins pull request #134
Opened 2023-01-07 13:37 UTC by lishoulong

in the file `transform/tests/fixture.rs`, we use the ecma::parser relative methods, but not define dependencies, causing error with `cargo test`.

```
use swc_core::{
    ecma::parser::{EsConfig, Syntax},
    ecma::transforms::testing::{test_fixture, FixtureTestConfig},
};
```

2023-01-07 13:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/plugins?pullRequest=134) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/plugins?pullRequest=134) before we can accept your contribution.<br/><hr/>**lishoulong** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/plugins?pullRequest=134) it.</sub>

2023-01-08 04:58 UTC, kdy1 requested changes
I think it should be a dev dep instead

2023-01-08 08:38 UTC, lishoulong commented
> I think it should be a dev dep instead

yes, I miss it, it only being used for testing.

2023-01-08 10:58 UTC, kdy1 commented
Can you sign the CLA?

2023-01-08 10:58 UTC, kdy1 approved these changes

2023-01-08 11:52 UTC, lishoulong commented
> Can you sign the CLA?

yeah, done it!

2023-01-08 11:59 UTC, merged