fix(emotion): Autolabel filename label generation
swc-project/plugins pull request #154
Opened 2023-03-05 22:51 UTC by Codex-

Currently the filename is taken with the extension, but this should be excluded.

Fixes #153

2023-03-05 22:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/plugins?pullRequest=154) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/plugins?pullRequest=154) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/plugins?pullRequest=154) it.</sub>

2023-03-06 01:06 UTC, kdy1 requested changes

2023-03-06 01:06 UTC, kdy1 commented on packages/emotion/transform/Cargo.toml
> +  "ecma_parser",
This is not used from the package.

2023-03-06 01:06 UTC, kdy1 commented on packages/emotion/transform/Cargo.toml
> +  "ecma_parser",
Please move this to dev deps

2023-03-06 01:28 UTC, Codex- commented on packages/emotion/transform/Cargo.toml
> +  "ecma_parser",
Sure thing, my mistake

2023-03-06 01:29 UTC, Codex- commented on packages/emotion/transform/Cargo.toml
> +  "ecma_parser",
Sure thing, my mistake.

Done!

2023-03-06 01:37 UTC, kdy1 commented on packages/emotion/transform/tests/fixture.rs
> +#[fixture("tests/labels/**/output.js")]
Can you document the reason you use `output.js` instead of `input.js`?

2023-03-06 02:47 UTC, Codex- commented on packages/emotion/transform/tests/fixture.rs
> +#[fixture("tests/labels/**/output.js")]
Comments added explaining the reasoning.

You may note that `[dirname]` is not tested here, this is because currently this implementation uses `[dir]` which is not what the docs or original plugin specify, I'll make a follow up PR fixing this with additional tests for this too.

2023-03-06 04:45 UTC, Codex- commented on packages/emotion/transform/tests/fixture.rs
> +#[fixture("tests/labels/**/output.js")]
Created a draft PR for fixing the other issue I describe here :)

2023-03-06 06:37 UTC, kdy1 approved these changes
Thank you!

2023-03-06 06:39 UTC, merged