test: Add tests on lazy from loadable-components
swc-project/plugins pull request #242
Opened 2023-12-18 13:52 UTC by Themezv

Add tests for #241

2023-12-18 13:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/plugins?pullRequest=242) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/plugins?pullRequest=242) before we can accept your contribution.<br/><hr/>**themezv** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/plugins?pullRequest=242) it.</sub>

2024-04-30 23:28 UTC, Themezv commented on .vscode/settings.json
> +  "editor.formatOnSave": false,
todo: revert

2024-05-08 08:41 UTC, kdy1 requested changes

2024-05-08 08:41 UTC, kdy1 commented on packages/loadable-components/src/lib.rs
> +    signatures: Option<Vec<Signature>>,
I think this should have `#[serde(default)]`

2024-06-10 00:07 UTC, kdy1 requested changes

2024-06-10 00:07 UTC, kdy1 commented on packages/loadable-components/src/lib.rs
> +    specifiers: HashSet<String>,
```suggestion
    specifiers: HashSet<Atom>,
```

2024-07-07 00:11 UTC, kdy1 approved these changes

2024-07-07 00:11 UTC, merged